In [1]:
1=2


SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (2752944879.py, line 1)

In [3]:
x = "Gone" 

if x == "Go": 
    print("Go")
else:
    print("Stop")
print("Mike")

Stop
Mike


In [6]:
x = 0 
while x < 2: 
    print(x)
    x = x+1


0
1


In [7]:
class Points(object):
    def __init__(self, x, y):
        self.x = x 
        self.y = y 


    def print_point(self): 
        print('x=', self.x, ' y=', self.y) 


p1 = Points("A", "B") 
p1.print_point()

x= A  y= B


In [8]:
for i, x in enumerate(['A', 'B', 'C']): 
    print(i, 2 * x)


0 AA
1 BB
2 CC


In [9]:
class Points(object): 
    def __init__(self, x, y): 
        self.x = x 
        self.y = y 
    def print_point(self): 
        print('x=', self.x, ' y=', self.y) 


p2 = Points(1, 2) 
p2.x = 'A' 
p2.print_point()


x= A  y= 2


In [12]:
def step(x): 
    if x > 0: 
        y = 1 
    else: 
        y = 0 
    return y

step(10)

1

In [13]:
a = 1 


def do(x): 
    return x + a 


print(do(1))

2


In [24]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])

In [29]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 2],
       [2, 2]])

array([1, 2])